services:
  postgres:
    image: postgres:18-alpine
    container_name: hornerodb-postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2
    restart: unless-stopped
    env_file: .env
    ports:
      - 1411:1411
    volumes:
      - "./data:/app/data"
    # Optional healthcheck
    healthcheck:
      test: [ "CMD", "/app/pocket-id", "healthcheck" ]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s

  hornerodb-server:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: hornerodb-server
      ports:
        - "8080:8080"
      environment:
        - DATABASE_URL=postgres://user:pass@db:5432/hornerodb
      depends_on:
        db:
          condition: service_healthy
volumes:
  postgres_data:
