services:
  postgres:
    image: postgres:alpine
    container_name: hornerodb-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hornero
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2
    container_name: hornerodb-pocketid
    restart: unless-stopped
    ports:
      - 1411:1411
    environment:
      - PUBLIC_APP_URL=http://localhost:1411
    volumes:
      - pocketid_data:/app/data
    healthcheck:
      test: [ "CMD", "/app/pocket-id", "healthcheck" ]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s

  hornerodb-server:
    image: lucahttp/hornerodb-server:latest
    container_name: hornerodb-server
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=hornero
      - POCKETID_ISSUER_URL=http://pocket-id:1411
      - POCKETID_PUBLIC_URL=http://localhost:1411
      - PORT=8080
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  pocketid_data:
