name: Docker CI

on:
  push:
    tags: [ 'v*.*.*' ]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      id-token: write
    with:
      output: image
      push: ${{ github.event_name != 'pull_request' }}
      platforms: linux/amd64,linux/arm64
      meta-images: lukaneco/hornerodb
      meta-tags: |
        type=ref,event=branch
        type=ref,event=pr
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          body: |
            ### 🚀 Docker Image
            La imagen de esta versión ya está disponible en Docker Hub:
            [lukaneco/hornerodb:${{ github.ref_name }}](https://hub.docker.com/r/lukaneco/hornerodb/tags?name=${{ github.ref_name }})
            
            En futuras versiones sumaremos los ejecutables para Windows, Linux y Mac.
          draft: false
          prerelease: false
          generate_release_notes: true
